### ISSUE TITLE
Switch to `time` from the `chrono` crate dependency

### ISSUE THREAD

**Issue by joseluis** [svix/rust-ksuid#1]
Hi! I noticed you're using the [`chrono`](https://crates.io/crates/chrono/) crate instead of the [`time`](https://crates.io/crates/time/) crate, and I just wanted to make sure you are aware of the security and maintenance problems of `chrono`. The following couple of reddit threads are a good summary:
- [Is the chrono crate unmaintained?](https://www.reddit.com/r/rust/comments/qamgyh/is_the_chrono_crate_unmaintained/)
- [Six weeks in, how are folks handling the time/chrono RUSTSEC advisories?](https://www.reddit.com/r/rust/comments/rmgarc/six_weeks_in_how_are_folks_handling_the/)

**Comment by tasn** [comment]
I was not aware, it should really be pulled from crates.io then!

Thanks a lot, will take a look at fixing it. This is exactly the feedback I wanted to get from r/rust, thanks a lot!
