### ISSUE TITLE
Implement `Display` for `svix_ksuid::Ksuid`

### ISSUE THREAD

**Issue by indiv0** [svix/rust-ksuid#2]
### Motivation

Hi! I'm not sure if this is intentional, but it looks like `Ksuid` doesn't implement `Display`.
This means that to print it out you need to do `format!("{}", ksuid.to_string())` rather than just `format!("{}", ksuid)`.
Not a big deal, but adds some verbosity.

### Proposal

Implementing `Display` should be as simple as moving the existing `to_string` logic into a `Display` impl.
I'm not sure if the type doesn't implement `Display` intentionally though. Perhaps this was done to avoid some API guarantees?

### Alternatives

N/A

**Comment by tasn** [comment]
Thanks for the suggestion, this was just a silly oversight!

Would you prefer to write the PR yourself (so you get the attribution), or have me write it?

**Comment by indiv0** [comment]
Go ahead, I'm OK with just having the feature added 😄
