### ISSUE TITLE
Serde feature missing

### ISSUE THREAD

**Issue by dahankzter** [svix/rust-ksuid#5]
## Bug Report

The docs say there should be a feature enabling `serde` support but cargo complains that there is no such feature.
I can't really tell if this has been removed or added as a permanent feature that's always on?

### Version

svix-ksuid v0.6.0

### Platform

Linux antiva 6.1.12-1-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Feb 14 21:59:10 UTC 2023 x86_64 GNU/Linux

### Description

Trying to add the crate ends up with:
```zsh
git:(main) cargo add svix-ksuid --features serde                         
    Updating crates.io index
      Adding svix-ksuid v0.6.0 to dependencies.
error: unrecognized feature for crate svix-ksuid: serde
no features available for crate svix-ksuid
```

**Comment by tasn** [comment]
Whoops, I guess we need to make a release to include https://github.com/svix/rust-ksuid/commit/16468002c4da26932ca1004fcae190f543565b78

One sec.

**Comment by tasn** [comment]
Fixed with 0.7.0, sorry about that!

**Comment by dahankzter** [comment]
Nice thank you @tasn and thanks for the nice crate!

**Comment by dahankzter** [comment]
```zsh
git:(main) cargo add svix-ksuid --features serde
    Updating crates.io index
      Adding svix-ksuid v0.7.0 to dependencies.
             Features:
             + serde
```

**Comment by tasn** [comment]
Yay, thank you for the kind words, and apologies for forgetting to make a release before!
